### PR TITLE
Ricardo/project

### PR DESCRIPTION
**Pull request by Ricoou**
I have an issue that happens with the code in this repository that didn't occur in the other codespaces. In Exercise 00 when running the code that is provided, 

```
import pandas as pd

# this CSV file contains semicolons instead of comas as separator
ds = pd.read_csv('assets/real_estate.csv', sep=';')
ds
```
I get this error:

 FileNotFoundError: [Errno 2] No such file or directory: 'assets/real_estate.csv'

All the code works in the other codespace, the path to the .csv file looks correct and the csv file is present in the asset folder. I tried looking up a solution, however, I wasn't able to find anything.

### CODE REVIEW

**Comment by sbarcelona11** [comment]
@Ricoou you use this code and try :
ds = pd.read_csv('../assets/real_estate.csv', sep=';')

**Comment by Ricoou** [comment]
@sbarcelona11 That worked, I have changed the code on al the exercises that use the pd.read_csv. Thanks!

**Comment by sbarcelona11** [comment]
@Ricoou for the Exercise 02. Which is cheapest house in the dataset?, can you add a filter of price > 0 to filter the prices.

**Comment by sbarcelona11** [comment]
@Ricoou for Exercise 09. can you delete the first three lines:

import pandas as pd
ds = pd.read_csv('../assets/real_estate.csv', sep=';')
ds

you don't need to redeclare the DataFrame

**Comment by sbarcelona11** [comment]
@Ricoou same as my last comment  in  the Exercise 13 and 16

**Pull request merged**
